### ISSUE TITLE
Avoid setting explicit size in px for the leaves because it is not scalable

### ISSUE THREAD

**Issue by antoineDeRengerve** [partnering/leaf-scale#5]
See changes induced by c7c1fb49af55125991650f438989a02d3028c18d

**Comment by antoineDeRengerve** [comment]
@nilpotence The changes that were made prevent from rescaling simply on a tablet.

I think a better setting may be found but will require to update applications at the same time.

**Comment by stephanieder** [comment]
With the use of custom style, this issue is not relevant anymore, closing
